version: '3.8'
services:
  wellnet-frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - wellnet-api
    environment:
      - PYTHONPATH=/app
    networks:
      - wellnet-network

  wellnet-api:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=production
    networks:
      - wellnet-network

networks:
  wellnet-network:
    driver: bridge